#pragma once
#include <string>
#include <vector>
#include <memory>
#include <functional>
#include <iostream>
#include <cstring>
#include <fstream>
#include <mutex>
#include <atomic>
#include <thread>
#include <chrono>
#include <regex>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <sys/stat.h>
#include <unistd.h>