# this is mostly used for  scanning the .env files is there some bad  secret left in the file or not 
# this solves all the attacks generated by the leakage of the secrets of the .env

import re
from typing import List, Dict, Any, Tuple
from .base_rule import BaseRule
from ..findings.finding import Finding

class HardcodedSecretsRule(BaseRule):
    @property
    def name(self) -> str:
        return "Hardcoded Secret"

    @property
    def severity(self) -> str:
        return "CRITICAL"

    @property
    def cwe_id(self) -> str:
        return "CWE-798"

    # Common secret patterns (name, regex, description)
    SECRET_PATTERNS = [
        # Generic high‑entropy strings
        (r"(?i)(api_key|apikey|secret|secret_key|token|password|passwd)\s*=\s*['\"]([A-Za-z0-9+/]{16,})['\"]",
         "Generic high‑entropy secret"),
        (r"(?i)(api_key|apikey|secret|secret_key|token|password|passwd)\s*:\s*['\"]([A-Za-z0-9+/]{16,})['\"]",
         "Generic high‑entropy secret (YAML)"),

        # AWS
        (r"AKIA[0-9A-Z]{16}", "AWS Access Key ID"),
        (r"(?i)aws_secret_access_key\s*=\s*['\"]([A-Za-z0-9/+=]{40})['\"]", "AWS Secret Access Key"),
        (r"(?i)aws_session_token\s*=\s*['\"]([A-Za-z0-9/+=]+)['\"]", "AWS Session Token"),

        # GitHub
        (r"github_personal_token_[a-zA-Z0-9]{40}", "GitHub Personal Access Token"),
        (r"gh[opsu]_[A-Za-z0-9]{36}", "GitHub OAuth / Fine‑grained token"),

        # Stripe
        (r"sk_live_[0-9a-zA-Z]{24}", "Stripe Live Secret Key"),
        (r"sk_test_[0-9a-zA-Z]{24}", "Stripe Test Secret Key"),
        (r"rk_live_[0-9a-zA-Z]{24}", "Stripe Restricted Key"),

        # Slack
        (r"xox[baprs]-[0-9a-zA-Z]{10,}", "Slack Token"),

        # Google
        (r"AIza[0-9A-Za-z\\-_]{35}", "Google API Key"),
        (r"-----BEGIN RSA PRIVATE KEY-----", "RSA Private Key"),
        (r"-----BEGIN OPENSSH PRIVATE KEY-----", "OpenSSH Private Key"),

        # Generic password assignments
        (r"(?i)password\s*=\s*['\"][^'\"]{8,}['\"](?!\s*#\s*(fake|example|test))",
         "Hardcoded Password (likely real)"),

        # JWT tokens
        (r"eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}", "JWT Token"),

        # Generic hex / base64 tokens
        (r"(?i)token\s*=\s*['\"][A-Fa-f0-9]{32,}['\"]", "Hex Token (32+ chars)"),
        (r"(?i)token\s*=\s*['\"][A-Za-z0-9+/]{24,}=['\"]", "Base64 Token"),
    ]

    def check(self, chunk: Dict[str, Any], context: Dict[str, Any]) -> List[Finding]:
        content = chunk.get("content", "")
        lines = content.splitlines()
        findings = []

        for line_num, line in enumerate(lines, start=chunk.get("start_line", 1)):
            # Skip lines that are obviously comments or documentation
            stripped = line.strip()
            if stripped.startswith(('#', '//', '/*', '*')) or "example" in stripped.lower():
                continue

            for pattern, desc in self.SECRET_PATTERNS:
                if re.search(pattern, line, re.IGNORECASE):
                    findings.append(self._create_finding(chunk, desc, line_num, line))
                    break  # Only report one pattern per line to avoid duplicates

        return findings

    def _create_finding(self, chunk, desc, line_num, code_line):
        return Finding(
            rule_name=self.name,
            severity=self.severity,
            file_path=chunk.get("file_path", ""),
            line_start=line_num,
            line_end=line_num,
            message=f"Hardcoded secret detected: {desc}",
            code_snippet=code_line.strip(),
            cwe_id=self.cwe_id,
        )